http:
  host: "0.0.0.0"
  port: "8081"
  
sapi:
  host: "assessment-sapi-v1.us-e2.cloudhub.io"
  port: ""
  path:
    assessment: "/api/assessments" 
    assessmentReport: "/api/assessments/reports"
    
  
