clientId: "ashdgvhgasdfhg"
clientSecret: "asjdhja32778234"
http:
  host: "0.0.0.0"
  port: "8082"

sapi:
  host: "0.0.0.0"
  port: "8081"
  path: 
    assessment: "/api/assessments"
    assessmentReport: "/api/assessments/reports"
